#!/usr/bin/env node
const tsv = require('fs').readFileSync('/dev/stdin', 'utf8')
const lines = tsv.trim().split('\n').map(line => line.split('\t'))
const datePrefix = process.argv[2]

const fields = lines[0]
function get (line, field) {
  const index = fields.indexOf(field)
  if (index === -1) throw new Error(`No such field: ${field}`)
  return line[index]
}

const latSpread = 0.0008
const longSpread = 0.00095

function octagon (lat, long, latSpread, longSpread) {
  return [[
    [long - (1.0 * longSpread), lat - (0.5 * latSpread)],
    [long - (1.0 * longSpread), lat + (0.5 * latSpread)],
    [long - (0.5 * longSpread), lat + (1.0 * latSpread)],
    [long + (0.5 * longSpread), lat + (1.0 * latSpread)],
    [long + (1.0 * longSpread), lat + (0.5 * latSpread)],
    [long + (1.0 * longSpread), lat - (0.5 * latSpread)],
    [long + (0.5 * longSpread), lat - (1.0 * latSpread)],
    [long - (0.5 * longSpread), lat - (1.0 * latSpread)],
    [long - (1.0 * longSpread), lat - (0.5 * latSpread)]
  ]]
}

process.stdout.write(JSON.stringify(
  {
    type: 'FeatureCollection',
    features: lines
      .slice(1)
      .filter(line => {
        return !datePrefix || get(line, 'Date').startsWith(datePrefix)
      })
      .map(line => {
        const long = parseFloat(get(line, 'Longitude'))
        const lat = parseFloat(get(line, 'Latitude'))
        return {
          type: 'Feature',
          geometry: {
            type: 'MultiPolygon',
            coordinates: [
              octagon(lat, long, latSpread, longSpread),
              octagon(lat, long, 2 * latSpread, 2 * longSpread),
              octagon(lat, long, 3 * latSpread, 3 * longSpread)
            ]
          },
          properties: {
            'stroke-opacity': 0.0,
            fill: '#FF0000',
            'fill-opacity': 0.025,
            date: get(line, 'Date')
          }
        }
      })
  }, null, 2
)
)
