#!/bin/sh
while read -r line; do
  address=$(echo "$line" | cut -f 1)
  date=$(echo "$line" | cut -f 2)
  event=$(echo "$line" | cut -f 3)
  isodate=$(date --iso-8601 -d "$date")
  printf "$isodate\t$event\t$address\n"
done
