#!/usr/bin/env node
const tsv = require('fs').readFileSync('/dev/stdin', 'utf8')
const lines = tsv.trim().split('\n').map(line => line.split('\t'))

const fields = lines[0]
function get (line, field) {
  const index = fields.indexOf(field)
  if (index === -1) throw new Error(`No such field: ${field}`)
  return line[index]
}

process.stdout.write(JSON.stringify(
  {
    type: 'FeatureCollection',
    features: lines
      .slice(1)
      .map(line => {
        return {
          type: 'Feature',
          geometry: {
            coordinates: [
              get(line, 'Longitude'),
              get(line, 'Latitude')
            ]
          },
          properties: {
            'marker-size': 'medium',
            'marker-color': 'FF0000',
            date: get(line, 'Date')
          }
        }
      })
  }, null, 2
)
)
